[build]
  command = "npm install"
  publish = "public"

[build.environment]
  NODE_VERSION = "20"

[functions]
  directory = "netlify/functions"
  node_bundler = "nft"
  included_files = ["views/**", "public/**", "node_modules/ejs/**"]

[[functions]]
  name = "server"
  timeout = 20

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200
  force = true
