[build]
  command = "npm install"
  publish = "public"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[functions]]
  name = "server"
  node_bundler = "nft"
  included_files = ["views/**", "public/**"]
  timeout = 26
